id: P005436
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 11:50:25.425664
source_metadata:
  id: bdr:W20555
  title: རྒྱུན་མཁོའི་ཆོ་ག་ཕྱག་ལེན་སྣ་ཚོགས
  author: ''
  volumes:
    fe30d485bcda4ac18ae9e3103640d852:
      image_group_id: I5508
      title: ''
      volume_number: 1
      total_pages: 302
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
